AVG_DELAY_THRESHOLD = 0.05
STD_DEV_THRESHOLD   = 0.05
BURST_THRESHOLD     = 20
MISTAKE_RATIO_MIN   = 0.05
WINDOW_SIZE         = 5
RISK_THRESHOLD      = 6

PAUSE_THRESHOLD     = 0.5
RYTHM_THRESHOLD     = 0.3
PAUSE_RATIO_THRESHOLD = 0.2